@endpoint = http://localhost:3006/api/v1/cars


###
POST {{endpoint}} HTTP/1.1
content-type: application/json

{ "make" : "make2",
"model" : "model2"
  }


###
GET  {{endpoint}} HTTP/3.0
content-type: application/json

###
GET  {{endpoint}}/6ab10951cdd48f3013b6505a HTTP/3.0
content-type: application/json



###

DELETE  {{endpoint}}/sillycarID HTTP/3.0
content-type: application/json

###

PUT  {{endpoint}}/6ab10951cdd48f3013b6505a HTTP/3.0
content-type: application/json

{ "model" : "changed model"
  }