@endpoint = http://localhost:3006/api/v1/cars

###
# @name postACar

POST {{endpoint}} HTTP/1.1
content-type: application/json

{ "make" : "make2",
"model" : "model2"
  }

###

@newCar = {{postACar.response.body._id}}

###
GET  {{endpoint}}/{{newCar}} HTTP/3.0
content-type: application/json

###
GET  {{endpoint}}/6ab1095dd4f3013b6505a HTTP/3.0
content-type: application/json



###

DELETE  {{endpoint}}/6ab10969cdd48013b6505b HTTP/3.0
content-type: application/json

###

PUT  {{endpoint}}/6ab10951cdd48f3013b6505 HTTP/3.0
content-type: application/json

{ "model" : "changed model"
  }